version: '3.7'

services:
#Data Flow
  nifi:
    image: apache/nifi:1.24.0
    container_name: nifi
    ports:
      - '8443:8443'
    volumes:
      - ./volumes/nifi/jdbc:/opt/jdbc
      - ./volumes/nifi/data:/opt/nifi/data
#      - ./volumes/nifi/certs:/opt/certs
#      - ./volumes/nifi/logs:/opt/nifi/logs
      - ./volumes/nifi/properties:/opt/nifi/nifi-current/properties  #credentials.properties
      - ./volumes/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./volumes/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./volumes/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ./volumes/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    environment:
      NIFI_WEB_HTTP_PORT: 8443

#      NIFI_WEB_HTTPS_PORT: 8443
#      SINGLE_USER_CREDENTIALS_USERNAME: Admin
#      SINGLE_USER_CREDENTIALS_PASSWORD: 123456789012

#      https://localhost:8443/nifi/
#      ./bin/nifi.sh set-single-user-credentials admin "123456789012"



#controle de vers찾o para o nifi
  nifi-registry:
    image: apache/nifi-registry:1.24.0
    container_name: nifi-registry
    ports:
      - '18080:18080'
    volumes:
     - ./volumes/nifi-registry/data:/data
     - ./volumes/nifi-registry/database:/opt/nifi-registry/nifi-registry-current/database
     - ./volumes/nifi-registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage
#     - ./volumes/nifi-registry/nifi-registry:/opt/nifi-registry/nifi-registry-current/nifi-registry
#     - ./volumes/nifi-registry/certs:/opt/certs
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: 18080
#      NIFI_REGISTRY_FLOW_PROVIDER: git
#      NIFI_REGISTRY_GIT_REMOTE_URL: https://github.com/diretoriorio_remoto.git
#      NIFI_REGISTRY_GIT_USER: xxx
#      NIFI_REGISTRY_GIT_PASSWORD: token
#      NIFI_REGISTRY_GIT_REPO: /opt/nifi-registry/nifi-registry-current/nifi-registry


# Reposit처rio de Dados N찾o Estruturados - Suporte S3
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_STORAGE_USE_HTTPS: False
    command: server /nifi.properties --console-address ":9001"

# Reposit처rio de Dados Estruturados
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres/data:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

