apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-nifi
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer